##### In this run we are going to read in the 100 results files generated by the HPC run 
# we are going to look at all the resultant PD losses and and create a 'master' edge scores data-frame

# Housekeeping
rm(list=ls())
graphics.off()
setwd("~/Documents/EDGE2/Chondrichthyes/")


# first things first: packages
#install.packages("wesanderson")
library(wesanderson)
library(ape)
library(caper)
library(data.table)
require(geiger)
require(pez)
require(phytools)
require(phylobase)


# read in csv with two columns: Species and GE 

load("ChSpecies.Rdata")

species.GE <- data.frame(Species = as.character(Species$Species), GE = Species$GE)
species.GE$Species <- as.character(species.GE$Species)


# load in the trees
load("1000_Chond_phylos.Rdata")

## prep storage

results.list <- list()
edge.spp.store <- list()

# run edge

for (x in 1:1000 ) { # 100: number of trees
  print(x)
  tree <- phy.block.1000[[x]]
  ed.scores <- ed.calc(tree)$spp
  edge.scores <- data.frame(ed.scores, GE = NA, EDGE = NA)
  
  for(i in 1:length(edge.scores$species)){
    # if the species in the tree is in the GE dataset
    if(edge.scores$species[i] %in% species.GE$Species){
      # if the GE is not NA (i.e. DD or unassessed species)
      if(!is.na(species.GE$GE[species.GE$Species == edge.scores$species[i]])){
        # assign GE to the dataset from the GE dataset
        edge.scores$GE[i] <- species.GE$GE[species.GE$Species == edge.scores$species[i]]
        # calculate EDGE score using ED and GE for the species
        edge.scores$EDGE[i] <- log(1+edge.scores$ED[i]) + (edge.scores$GE[i]*log(2))
      }
    }
  }
  edge.spp <- edge.scores[edge.scores$ED > median(edge.scores$ED),]
  edge.spp <- edge.scores[edge.scores$GE %in% c(2,3,4),]
  edge.spp <- edge.spp[order(edge.spp$EDGE, decreasing = T, na.last = T),]
  
  edge.spp.store[[x]] <- edge.spp
  results.list[[x]] <- edge.scores
}

save(results.list, edge.spp.store, file = "EDGE1_CH.Rdata")

########### looking at the results

all.edge.scores <- data.frame(matrix(nrow = length(results.list[[1]]$species), ncol = 1001))
all.edge.scores$X1 <- results.list[[1]]$species


# we need to unpack the results more delicately

for (i in 1:1000) {
  print(i)
  res <- results.list[[i]]
  for (x in 1:length(res$species)) {
    ref <- match(res$species[x], all.edge.scores$X1)
    all.edge.scores[ref, (i  + 1) ] <- res$EDGE[x]
  }
  }

##
all.edge.data <- data.frame(matrix(ncol = 1, nrow = length(results.list[[1]]$species)))
all.edge.data$Species <- all.edge.scores$X1

all.edge.data$means <- rowMeans(all.edge.scores[2:1001])
all.edge.data$mins <- apply(all.edge.scores[2:1001], 1, FUN=min)
all.edge.data$max <- apply(all.edge.scores[2:1001], 1, FUN=max)
all.edge.data <- all.edge.data[-1]

##### Calculate 

# get EDGE species - those with greater than median ED and in a threatened RL category (VU, EN, CR)

# check if the species are the same in the edge lists (in edge.spp.store)

top <- edge.spp.store[[1]]$species

for (i in 2:1000) {
  print(i)
  temp <- edge.spp.store[[i]]$species
  ref <- intersect(top, temp)
  if (length(ref) != 206) {
    print(paste(i, "is not same", sep = " "))
  }
}


# there are the same 206 species in each of the edge spp lists. Howver, the species in the top 50/100 are not the same!

edge.spp.scores <- subset(all.edge.data, (all.edge.data$Species %in% top == T))

top.50 <- edge.spp.scores[order(edge.spp.scores$means, decreasing = T, na.last = T),]
top.50 <- top.50[1:50,]

save(top.50, all.edge.data, all.edge.scores, edge.spp.store, file = "EDGE1_run_outputs_CH.Rdata")
